### ISSUE TITLE
structure name change?

### ISSUE THREAD

**Issue by MatoPlus** [jamesdorfman/musiqparti#3]
Small thing but what do people think about renaming template folders to `client` and `server` for `fontend` and `backend` respectively?

**Comment by jamesdorfman** [comment]
+1 sounds good to me, go ahead

**Comment by jamesdorfman** [comment]
Very little has been done yet, so make whatever changes you think are necessary.
Some changes are better than no changes ;)

Just tag someone in the group on discord to review any MRs.
